/**
 * \file pros/motors.h
 *
 * Contains C motor functions
 */

#ifndef _PROS_MOTORS_H_
#define _PROS_MOTORS_H_

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
namespace pros {
#endif

typedef enum motor_brake_mode_e {
  E_MOTOR_BRAKE_COAST = 0,
  E_MOTOR_BRAKE_BRAKE = 1,
  E_MOTOR_BRAKE_HOLD = 2,
  E_MOTOR_BRAKE_INVALID = INT32_MAX
} motor_brake_mode_e_t;

typedef enum {
  E_MOTOR_ENCODER_DEGREES = 0,
  E_MOTOR_ENCODER_ROTATIONS = 1,
  E_MOTOR_ENCODER_COUNTS = 2,
  E_MOTOR_ENCODER_INVALID = INT32_MAX
} motor_encoder_units_e_t;

typedef enum motor_gearset_e {
  E_MOTOR_GEARSET_36 = 0,
  E_MOTOR_GEAR_RED = E_MOTOR_GEARSET_36,
  E_MOTOR_GEAR_100 = E_MOTOR_GEARSET_36,
  E_MOTOR_GEARSET_18 = 1,
  E_MOTOR_GEAR_GREEN = E_MOTOR_GEARSET_18,
  E_MOTOR_GEAR_200 = E_MOTOR_GEARSET_18,
  E_MOTOR_GEARSET_06 = 2,
  E_MOTOR_GEAR_BLUE = E_MOTOR_GEARSET_06,
  E_MOTOR_GEAR_600 = E_MOTOR_GEARSET_06,
  E_MOTOR_GEARSET_INVALID = INT32_MAX,
} motor_gearset_e_t;

typedef enum motor_type_e {
  E_MOTOR_TYPE_V5 = 0,
  E_MOTOR_TYPE_EXP = 1,
  E_MOTOR_TYPE_INVALID = INT32_MAX,
} motor_type_e_t;

typedef enum motor_fault_e {
  E_MOTOR_FAULT_NO_FAULTS = 0x00,
  E_MOTOR_FAULT_MOTOR_OVER_TEMP = 0x01,
  E_MOTOR_FAULT_DRIVER_FAULT = 0x02,
  E_MOTOR_FAULT_OVER_CURRENT = 0x04,
  E_MOTOR_FAULT_DRV_OVER_CURRENT = 0x08
} motor_fault_e_t;

typedef enum motor_flag_e {
  E_MOTOR_FLAGS_NONE = 0x00,
  E_MOTOR_FLAGS_BUSY = 0x01,
  E_MOTOR_FLAGS_ZERO_VELOCITY = 0x02,
  E_MOTOR_FLAGS_ZERO_POSITION = 0x04
} motor_flag_e_t;

#ifdef PROS_USE_SIMPLE_NAMES
#ifdef __cplusplus
#define MOTOR_BRAKE_COAST pros::E_MOTOR_BRAKE_COAST
#define MOTOR_BRAKE_BRAKE pros::E_MOTOR_BRAKE_BRAKE
#define MOTOR_BRAKE_HOLD pros::E_MOTOR_BRAKE_HOLD
#define MOTOR_BRAKE_INVALID pros::E_MOTOR_BRAKE_INVALID
#define MOTOR_ENCODER_DEGREES pros::E_MOTOR_ENCODER_DEGREES
#define MOTOR_ENCODER_ROTATIONS pros::E_MOTOR_ENCODER_ROTATIONS
#define MOTOR_ENCODER_COUNTS pros::E_MOTOR_ENCODER_COUNTS
#define MOTOR_ENCODER_INVALID pros::E_MOTOR_ENCODER_INVALID
#define MOTOR_GEARSET_36 pros::E_MOTOR_GEARSET_36
#define MOTOR_GEAR_RED pros::E_MOTOR_GEAR_RED
#define MOTOR_GEAR_100 pros::E_MOTOR_GEAR_100
#define MOTOR_GEARSET_18 pros::E_MOTOR_GEARSET_18
#define MOTOR_GEAR_GREEN pros::E_MOTOR_GEAR_GREEN
#define MOTOR_GEAR_200 pros::E_MOTOR_GEAR_200
#define MOTOR_GEARSET_06 pros::E_MOTOR_GEARSET_06
#define MOTOR_GEARSET_6 pros::E_MOTOR_GEARSET_06
#define MOTOR_GEAR_BLUE pros::E_MOTOR_GEAR_BLUE
#define MOTOR_GEAR_600 pros::E_MOTOR_GEAR_600
#define MOTOR_GEARSET_INVALID pros::E_MOTOR_GEARSET_INVALID
#define MOTOR_TYPE_V5 pros::E_MOTOR_TYPE_V5
#define MOTOR_TYPE_EXP pros::E_MOTOR_TYPE_EXP
#define MOTOR_TYPE_INVALID pros::E_MOTOR_TYPE_INVALID
#define MOTOR_FAULT_NO_FAULTS pros::E_MOTOR_FAULT_NO_FAULTS
#define MOTOR_FAULT_MOTOR_OVER_TEMP pros::E_MOTOR_FAULT_MOTOR_OVER_TEMP
#define MOTOR_FAULT_DRIVER_FAULT pros::E_MOTOR_FAULT_DRIVER_FAULT
#define MOTOR_FAULT_OVER_CURRENT pros::E_MOTOR_FAULT_OVER_CURRENT
#define MOTOR_FAULT_DRV_OVER_CURRENT pros::E_MOTOR_FAULT_DRV_OVER_CURRENT
#define MOTOR_FLAGS_NONE pros::E_MOTOR_FLAGS_NONE
#define MOTOR_FLAGS_BUSY pros::E_MOTOR_FLAGS_BUSY
#define MOTOR_FLAGS_ZERO_VELOCITY pros::E_MOTOR_FLAGS_ZERO_VELOCITY
#define MOTOR_FLAGS_ZERO_POSITION pros::E_MOTOR_FLAGS_ZERO_POSITION
#else
#define MOTOR_BRAKE_COAST E_MOTOR_BRAKE_COAST
#define MOTOR_BRAKE_BRAKE E_MOTOR_BRAKE_BRAKE
#define MOTOR_BRAKE_HOLD E_MOTOR_BRAKE_HOLD
#define MOTOR_BRAKE_INVALID E_MOTOR_BRAKE_INVALID
#define MOTOR_ENCODER_DEGREES E_MOTOR_ENCODER_DEGREES
#define MOTOR_ENCODER_ROTATIONS E_MOTOR_ENCODER_ROTATIONS
#define MOTOR_ENCODER_COUNTS E_MOTOR_ENCODER_COUNTS
#define MOTOR_ENCODER_INVALID E_MOTOR_ENCODER_INVALID
#define MOTOR_GEARSET_36 E_MOTOR_GEARSET_36
#define MOTOR_GEAR_RED E_MOTOR_GEAR_RED
#define MOTOR_GEAR_100 E_MOTOR_GEAR_100
#define MOTOR_GEARSET_18 E_MOTOR_GEARSET_18
#define MOTOR_GEAR_GREEN E_MOTOR_GEAR_GREEN
#define MOTOR_GEAR_200 E_MOTOR_GEAR_200
#define MOTOR_GEARSET_06 E_MOTOR_GEARSET_06
#define MOTOR_GEARSET_6 E_MOTOR_GEARSET_06
#define MOTOR_GEAR_BLUE E_MOTOR_GEAR_BLUE
#define MOTOR_GEAR_600 E_MOTOR_GEAR_600
#define MOTOR_GEARSET_INVALID E_MOTOR_GEARSET_INVALID
#define MOTOR_TYPE_V5 E_MOTOR_TYPE_V5
#define MOTOR_TYPE_EXP E_MOTOR_TYPE_EXP
#define MOTOR_TYPE_INVALID E_MOTOR_TYPE_INVALID
#define MOTOR_FAULT_NO_FAULTS E_MOTOR_FAULT_NO_FAULTS
#define MOTOR_FAULT_MOTOR_OVER_TEMP E_MOTOR_FAULT_MOTOR_OVER_TEMP
#define MOTOR_FAULT_DRIVER_FAULT E_MOTOR_FAULT_DRIVER_FAULT
#define MOTOR_FAULT_OVER_CURRENT E_MOTOR_FAULT_OVER_CURRENT
#define MOTOR_FAULT_DRV_OVER_CURRENT E_MOTOR_FAULT_DRV_OVER_CURRENT
#define MOTOR_FLAGS_NONE E_MOTOR_FLAGS_NONE
#define MOTOR_FLAGS_BUSY E_MOTOR_FLAGS_BUSY
#define MOTOR_FLAGS_ZERO_VELOCITY E_MOTOR_FLAGS_ZERO_VELOCITY
#define MOTOR_FLAGS_ZERO_POSITION E_MOTOR_FLAGS_ZERO_POSITION
#endif
#endif

int32_t motor_move(int8_t port, int32_t voltage);
int32_t motor_move_velocity(int8_t port, int32_t velocity);
double motor_get_position(int8_t port);
double motor_get_actual_velocity(int8_t port);
int32_t motor_get_voltage(int8_t port);
int32_t motor_set_zero_position(int8_t port, double position);
int32_t motor_tare_position(int8_t port);
int32_t motor_set_brake_mode(int8_t port, motor_brake_mode_e_t mode);
int32_t motor_set_encoder_units(int8_t port, motor_encoder_units_e_t units);
int32_t motor_set_gearset(int8_t port, motor_gearset_e_t gearset);

#ifdef __cplusplus
}
}  // namespace pros
#endif

#endif  // _PROS_MOTORS_H_
